version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input &&
             gunicorn core.wsgi:application --timeout 60 --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static_files
    expose:
      - 8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.4
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static_files
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  db:
    driver: local
  static_volume:
    driver: local
