version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --no-input &&
             gunicorn core.wsgi:application --timeout 60 --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static_files
    expose:
      - 8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:15.4
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static_files
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db:
    driver: local
  static_volume:
    driver: local
