# Generated by Django 4.2.5 on 2023-09-10 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('display', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('balance_lock', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extrinsic_index', models.CharField(max_length=30, unique=True)),
                ('asset_symbol', models.CharField(blank=True, max_length=20)),
                ('module', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('usd_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='monitor.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='monitor.account')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'db_table': 'transfer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor.account')),
            ],
            options={
                'verbose_name': 'Dapp',
                'verbose_name_plural': 'Dapps',
                'db_table': 'dapp',
                'ordering': ['name'],
            },
        ),
    ]
