# Generated by Django 4.2.8 on 2023-12-09 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TONAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'TONAccount',
                'verbose_name_plural': 'TONAccounts',
                'db_table': 'ton_account',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TONTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash', models.CharField(max_length=100, unique=True)),
                ('source_address', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=30)),
            ],
            options={
                'verbose_name': 'TONTransfer',
                'verbose_name_plural': 'TONTransfers',
                'db_table': 'ton_transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
