# Generated by Django 4.2.8 on 2023-12-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_tonaccount_tontransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonaccount',
            name='address_raw',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
